image: docker:stable

stages:
  - build
  - deploy

before_script:
  - echo "$REG_PASSWD" | docker login --username $REG_USER --password-stdin dockregistry.javerik.space

build:test:
  stage: build
  except:
    - main
  script:
    - docker build --no-cache -t test_atos_builder .
    - docker build --no-cache -t test_atos_pkg_builder -f Dockerfile.pkgbuild .

deploy:
  stage: deploy
  only:
    - main
  script:
    - docker build --no-cache -t dockregistry.javerik.space/builder/linux/atos_builder:latest .
    - docker push dockregistry.javerik.space/builder/linux/atos_builder:latest
    - docker build --no-cache -t dockregistry.javerik.space/builder/linux/atos_pkg_builder:latest -f Dockerfile.pkgbuild .
    - docker push dockregistry.javerik.space/builder/linux/atos_pkg_builder:latest

