FROM library/archlinux:base-devel-20230910.0.177821

RUN echo 'Server = https://europe.mirror.pkgbuild.com/$repo/os/$arch' > /etc/pacman.d/mirrorlist

RUN pacman-key --init && pacman -Sy archlinux-keyring --noconfirm && pacman -Syu --noconfirm && pacman -Sy bash cloud-utils gtk3 libxss nss node-gyp yarn libxkbfile libnotify lsof xdg-utils alsa-lib --noconfirm && useradd -ms /bin/bash pkgbuilder

WORKDIR /home/pkgbuilder

ENTRYPOINT [""]
