FROM library/archlinux:base-devel-20230910.0.177821

RUN pacman -Syu --noconfirm && pacman -Sy bash cloud-utils --noconfirm && useradd -ms /bin/bash pkgbuilder

WORKDIR /home/pkgbuilder

ENTRYPOINT [""]
